# Dependabot configuration for automated dependency updates
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Composer dependencies (PHP packages)
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Mexico_City"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "composer"
      - "automated"
    commit-message:
      prefix: "deps"
      prefix-development: "deps"
      include: "scope"
    # Group minor and patch updates together
    groups:
      composer-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    # Critical packages - always create separate PRs for major updates
    ignore:
      # PHPUnit 10+ incompatible with WordPress Test Suite (WP_UnitTestCase)
      # WordPress Test Suite requires PHPUnit 9.x
      - dependency-name: "phpunit/phpunit"
        update-types: ["version-update:semver-major"]
      # PHPStan 2.x requires PHP 8.1+ and has breaking changes
      # Keep at 1.x until ready for major migration
      - dependency-name: "phpstan/phpstan"
        update-types: ["version-update:semver-major"]
      # Settings Hub and GitHub Updater - manual review for major updates
      - dependency-name: "silverassist/wp-settings-hub"
        update-types: ["version-update:semver-major"]
      - dependency-name: "silverassist/wp-github-updater"
        update-types: ["version-update:semver-major"]

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:30"
      timezone: "America/Mexico_City"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "github-actions"
      - "automated"
    commit-message:
      prefix: "ci"
      include: "scope"
